### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by leecannon** [goto-bus-stop/setup-zig#44]
It would be great if this action cached the zig install so if the version has not changed no download is required.

**Comment by andrewrk** [comment]
Hi, our AWS bandwidth bill is pretty high. Would be super nice if a mirror was used or caching was in place.

**Comment by goto-bus-stop** [comment]
yikes, sorry about that :S the action does use github's tool caching but it seems to not work and I couldn't really figure out why that is when i looked last week. I'll give it another shot today...

**Comment by goto-bus-stop** [comment]
I think I misunderstood what the tool cache is for. It just looks up tools in the preinstalled images. It might be worthwhile to ask github to include zig releases in that, but that could take a while (and they might not agree that it's popular enough).
i just made this action quickly when i tried out zig back then and am not the biggest actions expert 😅 

So using the separate gh actions caching might be required, I aaaaalso thought that that costs users money, but afaict github will just evict caches past a given size limit, so it could be fine to add it by default in a minor release. I can experiment with that over the weekend

**Comment by andrewrk** [comment]
Thanks for looking into it!

**Comment by goto-bus-stop** [comment]
Apologies that it took a while. I published new versions on the v1 and v2 branch so anyone using `@v1` or `@v2` in their workflows now automatically gets caching by default. This time it should have a pretty significant impact.

**Comment by leecannon** [comment]
Just checked and it looks like this is working :+1:
