### ISSUE TITLE
`cache: false` not working

### ISSUE THREAD

**Issue by linusg** [goto-bus-stop/setup-zig#55]
`Boolean("false")` in JS is `true`, not `false`. Needs to pass `useCache === "true"` to `downloadZig()`.

https://github.com/goto-bus-stop/setup-zig/blob/14a1906c0dcb0d690f5e9733c5cd0e6484ac6406/index.js#L65-L70

**Comment by goto-bus-stop** [comment]
Thanks, fixed in 2.1.1!
